### ISSUE TITLE
Can't find requirements.txt

### ISSUE THREAD

**Issue by yybr1019** [ShawnHXH/GNN-CCA#2]
Hi, I am very interested in this topic.
But i can't find requirements.txt in your github.
Could you provide requirements.txt?

Thank you so much!

**Comment by shawnh2** [comment]
Thanks for your reminder！

The `requirement.txt` file has been uploaded, also the `README.md` file has been updated.

**Comment by yybr1019** [comment]
Thank you for the quick reply.
👍
